import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'extended_game_dto.g.dart';

@JsonSerializable()
class ExtendedGameDto {
  ExtendedGameDto(
    this.gameNumber,
    this.pitch,
    this.teamA,
    this.teamB,
    this.leagueName,
    this.ageGroupName,
    this.pointsTeamA,
    this.pointsTeamB,
  );

  int gameNumber;
  String pitch;
  String teamA;
  String teamB;
  String leagueName;
  String ageGroupName;
  int pointsTeamA;
  int pointsTeamB;

  factory ExtendedGameDto.fromJson(Map<String, dynamic> json) =>
      _$ExtendedGameDtoFromJson(json);

  Map<String, dynamic> toJson() => _$ExtendedGameDtoToJson(this);
}
