version: '3.8'

services:
  turnier-frontend:
    image: ghcr.io/jf-landkreis-karlsruhe/turnier-frontend:latest
    ports:
      - "8081:80"  # Mapping port 8081 on the host to port 80 on the container
    environment:
      - BACKEND_URL=localhost:8080
    depends_on:
      - turnier-backend

  turnier-backend:
    image: ghcr.io/jf-landkreis-karlsruhe/turnier-backend:latest
    ports:
      - "8080:8080"  # Mapping port 8080 on the host to port 8080 on the container
    environment:
      - SPRING_APPLICATION_NAME=turnier-backend
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - SPRING_DATASOURCE_URL=jdbc:mariadb://turnier-maria:3306/turnier
    depends_on:
      - database

  database:
    image: mariadb:latest
    container_name: turnier-maria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: turnier
    ports:
      - "3306:3306"
