import 'package:json_annotation/json_annotation.dart';
import 'package:tournament_manager/src/serialization/league_dto.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'match_schedule_dto.g.dart';

@JsonSerializable(explicitToJson: true)
class MatchScheduleDto {
  MatchScheduleDto(this.matchRound);

  int matchRound;
  List<LeagueDto> leagueSchedules = [];

  factory MatchScheduleDto.fromJson(Map<String, dynamic> json) =>
      _$MatchScheduleDtoFromJson(json);

  Map<String, dynamic> toJson() => _$MatchScheduleDtoToJson(this);
}
