import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'match_schedule_dto.g.dart';

@JsonSerializable()
class MatchScheduleDto {
  MatchScheduleDto();

  factory MatchScheduleDto.fromJson(Map<String, dynamic> json) =>
      _$MatchScheduleDtoFromJson(json);

  Map<String, dynamic> toJson() => _$MatchScheduleDtoToJson(this);
}
