import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'match_schedule_dto.g.dart';

@JsonSerializable()
class MatchScheduleDto {
  MatchScheduleDto(
    this.field,
    this.team1,
    this.pointsTeam1,
    this.team2,
    this.pointsTeam2,
    this.startTime,
  );

  String field;
  String team1;
  int pointsTeam1;
  String team2;
  int pointsTeam2;
  String startTime;

  factory MatchScheduleDto.fromJson(Map<String, dynamic> json) =>
      _$MatchScheduleDtoFromJson(json);

  Map<String, dynamic> toJson() => _$MatchScheduleDtoToJson(this);
}
