import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'match_schedule_entry_dto.g.dart';

@JsonSerializable()
class MatchScheduleEntryDto {
  MatchScheduleEntryDto(
    this.field,
    this.team1,
    this.pointsTeam1,
    this.team2,
    this.pointsTeam2,
    this.startTime,
  );

  String field;
  String team1;
  int pointsTeam1;
  String team2;
  int pointsTeam2;
  String startTime;

  factory MatchScheduleEntryDto.fromJson(Map<String, dynamic> json) =>
      _$MatchScheduleEntryDtoFromJson(json);

  Map<String, dynamic> toJson() => _$MatchScheduleEntryDtoToJson(this);
}
