import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'tournament_dto.g.dart';

@JsonSerializable(explicitToJson: true)
class TournamentDto {
  TournamentDto(this.id);

  int id;
  List<int> ageGroups = [];

  factory TournamentDto.fromJson(Map<String, dynamic> json) =>
      _$TournamentDtoFromJson(json);

  Map<String, dynamic> toJson() => _$TournamentDtoToJson(this);
}
