import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'age_group_dto.g.dart';

@JsonSerializable()
class AgeGroupDto {
  AgeGroupDto(this.name);

  String name;

  factory AgeGroupDto.fromJson(Map<String, dynamic> json) =>
      _$AgeGroupDtoFromJson(json);

  Map<String, dynamic> toJson() => _$AgeGroupDtoToJson(this);
}
