import 'package:json_annotation/json_annotation.dart';
import 'package:tournament_manager/src/serialization/referee/pitch_dto.dart';
import 'package:tournament_manager/src/serialization/referee/team_dto.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'game_dto.g.dart';

@JsonSerializable(explicitToJson: true)
class GameDto {
  GameDto(
    this.gameNumber,
    this.pitch,
    this.teamA,
    this.teamB,
  );

  int gameNumber;
  PitchDto pitch;
  TeamDto teamA;
  TeamDto teamB;

  factory GameDto.fromJson(Map<String, dynamic> json) =>
      _$GameDtoFromJson(json);

  Map<String, dynamic> toJson() => _$GameDtoToJson(this);
}
