import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'game_settings_dto.g.dart';

@JsonSerializable()
class GameSettingsDto {
  GameSettingsDto(
    this.startTime,
    this.breakTime,
    this.playTime,
  );

  DateTime startTime;
  int breakTime;
  int playTime;

  factory GameSettingsDto.fromJson(Map<String, dynamic> json) =>
      _$GameSettingsDtoFromJson(json);

  Map<String, dynamic> toJson() => _$GameSettingsDtoToJson(this);
}
