import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'league_dto.g.dart';

@JsonSerializable()
class LeagueDto {
  LeagueDto(this.name);

  String name;

  factory LeagueDto.fromJson(Map<String, dynamic> json) =>
      _$LeagueDtoFromJson(json);

  Map<String, dynamic> toJson() => _$LeagueDtoToJson(this);
}
