import 'package:json_annotation/json_annotation.dart';
import 'package:tournament_manager/src/serialization/referee/game_dto.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'round_dto.g.dart';

@JsonSerializable(explicitToJson: true)
class RoundDto {
  RoundDto(
    this.name,
  );

  String name;
  List<GameDto> games = [];

  factory RoundDto.fromJson(Map<String, dynamic> json) =>
      _$RoundDtoFromJson(json);

  Map<String, dynamic> toJson() => _$RoundDtoToJson(this);
}
