import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'team_dto.g.dart';

@JsonSerializable(explicitToJson: true)
class TeamDto {
  TeamDto(
    this.name,
  );

  String name;

  factory TeamDto.fromJson(Map<String, dynamic> json) =>
      _$TeamDtoFromJson(json);

  Map<String, dynamic> toJson() => _$TeamDtoToJson(this);
}
