import 'package:json_annotation/json_annotation.dart';
import 'package:tournament_manager/src/serialization/referee/age_group_dto.dart';
import 'package:tournament_manager/src/serialization/referee/league_dto.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'team_dto.g.dart';

@JsonSerializable(explicitToJson: true)
class TeamDto {
  TeamDto(
    this.name,
    this.ageGroup,
    this.league,
  );

  String name;
  AgeGroupDto ageGroup;
  LeagueDto league;

  factory TeamDto.fromJson(Map<String, dynamic> json) =>
      _$TeamDtoFromJson(json);

  Map<String, dynamic> toJson() => _$TeamDtoToJson(this);
}
