name: Build turnier-frontend

on:
  push:
    tags:
      - "*"
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set Tag as Environment Variable
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: './frontend'
          platforms: linux/amd64,linux/arm64
          push: startsWith(github.ref, 'refs/tags/')
          tags: |
            ghcr.io/${{ github.repository_owner }}/turnier-frontend:${{ env.TAG_NAME }}
            ghcr.io/${{ github.repository_owner }}/turnier-frontend:latest
