import 'package:json_annotation/json_annotation.dart';

// autogenerated with 'dart run build_runner build --delete-conflicting-outputs'
part 'match_schedule_entry_dto.g.dart';

@JsonSerializable()
class MatchScheduleEntryDto {
  MatchScheduleEntryDto(
    this.pitchName,
    this.teamAName,
    this.teamBName,
    this.startTime,
  );

  String pitchName;
  String teamAName;
  String teamBName;
  String startTime;

  factory MatchScheduleEntryDto.fromJson(Map<String, dynamic> json) =>
      _$MatchScheduleEntryDtoFromJson(json);

  Map<String, dynamic> toJson() => _$MatchScheduleEntryDtoToJson(this);
}
